# 基础镜像
FROM nginx
# author
MAINTAINER nrpt

# 挂载目录
VOLUME /home/nrpt/projects/nrpt-ui
# 创建目录
RUN mkdir -p /home/nrpt/projects/nrpt-ui
# 指定路径
WORKDIR /home/nrpt/projects/nrpt-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/nrpt/projects/nrpt-ui
