# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER nrpt

# 挂载目录
VOLUME /home/nrpt
# 创建目录
RUN mkdir -p /home/nrpt
# 指定路径
WORKDIR /home/nrpt
# 复制jar文件到路径
COPY ./jar/nrpt-visual-monitor.jar /home/nrpt/nrpt-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","nrpt-visual-monitor.jar"]